input {
  # Nginx에서 쏜 syslog(UDP) 데이터를 50000 포트에서 받습니다.
  syslog {
    port => 50000   # Logstash 컨테이너 내부 50000번 포트 열고 대기
    type => "nginx" # 들어오는 데이터에 "nginx"라는 이름표
  }

  tcp {
      port => 5044  # Logstash 컨테이너 내부 5044번 포트 열고 대기
      codec => json_lines   # 번역기(codec): 들어오는 데이터가 JSON 구조로 분석
      type => "spring"
  }

   tcp {
       port => 5045 # Logstash 컨테이너 내부 5045번 포트 열고 대기
       codec => json_lines
       type => "ai"
   }
}

filter {
  # (나중에 로그 포맷을 예쁘게 자르고 싶을 때 여기에 작성)
}

# [출구 설정] 데이터를 Elasticsearch 창고에 저장하는 곳
output {
  # 1. 터미널 화면에 로그가 잘 들어오는지 텍스트로 찍어줍니다. (디버깅용)
  stdout {
    codec => rubydebug
  }

  # 이름표(type)에 따라 엘라스틱서치의 다른 인덱스(엑셀 파일의 시트 같은 개념)로 분류해서 저장
  if [type] == "nginx" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]    # 창고 주소
      index => "nginx-logs-%{+YYYY.MM.dd}"      # 'nginx-logs-오늘날짜' 라는 이름의 표에 저장
    }
  } else if [type] == "spring" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "spring-logs-%{+YYYY.MM.dd}"
    }
  } else if [type] == "ai" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "ai-logs-%{+YYYY.MM.dd}"
    }
  }
}