spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: bangjwo

  datasource:
    url: jdbc:mysql://localhost:3306/bangjwo?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: none
        default_batch_fetch_size: 1000