spring:
  web:
    mvc:
      servlet:
        path: /api/v1

  config:
    import: optional:file:.env[.properties]

  application:
    name: bangjwo

  datasource:
    url: jdbc:mysql://localhost:13306/bangjwo?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME:bangjwo}:${MONGO_INITDB_ROOT_PASSWORD:1234}@localhost:27017/admin

  main:
    allow-bean-definition-overriding: true

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

aws:
  access:
    key: ${AWS_ACCESS_KEY}
  secret:
    key: ${AWS_SECRET_KEY}
  s3:
    bucket: "bangjwo-s3"
  region: "ap-northeast-2"


