spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: bangjwo

  datasource:
    url: jdbc:mysql://localhost:3306/bangjwo?serverTimezone=UTC&characterEncoding=UTF-8
    username: bangjwo
    password: 1234
    hikari:
      maximum-pool-size: 10

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  sql:
    init:
      mode: always
